"""New Migration

Revision ID: f116ac89a800
Revises: 
Create Date: 2023-11-13 19:54:55.818088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f116ac89a800'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_id'), 'book', ['id'], unique=False)
    op.drop_table('Kits')
    op.drop_table('Cirurgia')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cirurgia',
    sa.Column('id_Cirurgia', sa.CHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('CRM_Medico', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('CPF_Paciente', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Sala_Hospital', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('Data_Hora', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('id kit', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('Tipo_Cirurgia', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id kit'], ['Kits.id kit'], name='cirurgia_id kit_foreign'),
    sa.PrimaryKeyConstraint('id_Cirurgia', name='Cirurgia_pkey')
    )
    op.create_table('Kits',
    sa.Column('id kit', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('matching', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('nome_instrumento', sa.CHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id kit', name='Kits_pkey')
    )
    op.drop_index(op.f('ix_book_id'), table_name='book')
    op.drop_table('book')
    op.drop_table('author')
    # ### end Alembic commands ###
